# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 


import numpy as np
np.random.seed(42)
# Let's define a one-dimensional array 

list_1=[50,60,70,80]
list_1

[50, 60, 70, 80]

In [2]:
# Let's create a numpy array from the list "my_list"

my_numpy_array=np.array(list_1)
my_numpy_array

array([50, 60, 70, 80])

In [3]:
type(my_numpy_array)

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 
my_matrix=np.array([[2,5,8],[7,3,6]])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [5]:
arr2=np.array([[3,7,9,3],[4,3,2,2]])
arr2

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS

In [6]:
# "rand()" uniform distribution between 0 and 1
x=np.random.rand(20)
x

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914])

In [7]:
# you can create a matrix of random number as well
xx=np.random.rand(3,3)
xx

array([[0.61185289, 0.13949386, 0.29214465],
       [0.36636184, 0.45606998, 0.78517596],
       [0.19967378, 0.51423444, 0.59241457]])

In [8]:
# "randint" is used to generate random integers between upper and lower bounds
xxx=np.random.randint(1,300)
xxx

131

In [9]:
# "randint" can be used to generate a certain number of random itegers as follows

xxxx=np.random.randint(1,100,15)
xxxx

array([51,  7, 21, 73, 39, 18,  4, 89, 60, 14,  9, 90, 53,  2, 84])

In [10]:
# np.arange creates an evenly spaced values within a given interval
k=np.arange(1,50)
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
# create a diagonal of ones and zeros everywhere else
n=np.eye(7)
n

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [12]:
# Matrix of ones
n=np.ones((4,4))
n

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# Array of zeros
n=np.zeros(5)
n

array([0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [14]:
x = 10  # Example positive integer for a non-interactive notebook run
print(f"Using x = {x}")

Using x = 10

In [15]:
arrayy = np.random.randint(0, x + 1, 10)
arrayy

array([6, 7, 2, 0, 3, 1, 7, 3, 1, 5])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [16]:
# np.arange() returns an evenly spaced values within a given interval
o=np.arange(1,10)

In [17]:
v = np.arange(1, 10)

In [18]:
array_sum = o + v
array_sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
squired=o**2
squired

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [20]:
z = np.exp(v)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [21]:
x = np.array([5, 7, 20])
y = np.array([9, 15, 4])

In [22]:
z = np.sqrt(x**2 + y**2)
z

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING

In [23]:
my_arr=np.array([3,5,6,7])
my_arr

array([3, 5, 6, 7])

In [24]:
# Access specific index from the numpy array
my_arr[2]

np.int64(6)

In [25]:
# Starting from the first index 0 up until and NOT including the last element
my_arr[0:4]

array([3, 5, 6, 7])

In [26]:
my_arr[0:4] = 7
my_arr

array([7, 7, 7, 7])

In [27]:
matrix = np.random.randint(1, 10, (4, 4))
matrix

array([[6, 4, 6, 2],
       [2, 4, 8, 7],
       [9, 8, 5, 2],
       [5, 8, 9, 9]])

In [28]:
# Get a row from a mtrix
matrix[0]

array([6, 4, 6, 2])

In [29]:
# Get one element
matrix[0][0]
#find element by index of rows and colums

np.int64(6)

MINI CHALLENGE #4: Replace the last row of the matrix with zeros. The solution is shown below.

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [30]:
matrix = np.random.randint(1, 10, (5, 5))
matrix
# Filter elements greater than 7
new_matrix = matrix[matrix > 7]
new_matrix

array([9, 9, 8, 8, 8, 8, 9, 9, 8, 8])

In [31]:
# Obtain odd elements only

new_matrix=matrix[matrix%2==1]
new_matrix

array([1, 9, 7, 9, 1, 3, 1, 3, 3, 1, 5, 7, 9, 7, 9, 1, 7, 7])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [32]:
x = np.array([[2, 30, 20, -2, -4],
              [3, 4, 40, -3, -2],
              [-3, 4, -6, 90, 10],
              [25, 45, 34, 22, 12],
              [13, 24, 22, 32, 37]])
x[x < 0] = 0
x[x % 2 == 1] = -2
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [33]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [34]:
import pandas as pd

In [35]:
bank_client = pd.DataFrame({'id': [111, 222, 444],
                            'name': ['Habiba', 'Gon', 'Sara']})
bank_client

    id    name
0  111  Habiba
1  222     Gon
2  444    Sara

In [36]:
type(bank_client)

pandas.core.frame.DataFrame

In [37]:
# Display the first row
bank_client.head(1)

    id    name
0  111  Habiba

In [38]:
# Display the last row
bank_client.tail(1)

    id  name
2  444  Sara

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [39]:
# Pandas is used to read a csv file and store data in a DataFrame

In [40]:
import pandas as pd

In [41]:
# Read tabular data using read_html

In [42]:
from pathlib import Path
csv_path = Path('bank_client_data.csv')
if not csv_path.exists():
    pd.DataFrame({'Client ID': [1, 2, 3], 'Name': ['Habiba', 'Ali', 'Mona'], 'Net Worth': [1000, 5000, 10000]}).to_csv(csv_path, index=False)
df_csv = pd.read_csv(csv_path)
df_csv

   Client ID    Name  Net Worth
0          1  Habiba       1000
1          2     Ali       5000
2          3    Mona      10000

In [43]:
url = 'https://www.ssa.gov/oact/progdata/nra.html'
try:
    df_html = pd.read_html(url)
    df_html[0].head()
except Exception as e:
    print(f'Could not retrieve the live webpage; using a small illustrative fallback table. Details: {type(e).__name__}')
    df_html = [pd.DataFrame({'Year': [2024, 2025, 2026], 'Retirement Age': ['66 years 8 months', '66 years 10 months', '67 years']})]
    df_html[0].head()

Could not retrieve the live webpage; using a small illustrative fallback table. Details: URLError

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

In [44]:
try:
    retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
except Exception as e:
    print(f'Could not retrieve live retirement data; using an illustrative fallback table. Details: {type(e).__name__}')
    retirement_df = [pd.DataFrame({'Year': [2024, 2025, 2026], 'Retirement Age': ['66 years 8 months', '66 years 10 months', '67 years']})]
retirement_df[0]

Could not retrieve live retirement data; using an illustrative fallback table. Details: URLError

   Year      Retirement Age
0  2024   66 years 8 months
1  2025  66 years 10 months
2  2026            67 years

# TASK #8: PANDAS OPERATIONS

In [45]:
# Let's define a dataframe as follows:
raw_data = {'Client ID': [1, 2, 3, 4], 'Net Worth': [1000, 5000, 10000, 3000]}
bank_client_df = pd.DataFrame(raw_data)
bank_client_df

   Client ID  Net Worth
0          1       1000
1          2       5000
2          3      10000
3          4       3000

In [46]:
# Pick certain rows that satisfy a certain criteria 
filtered_df = bank_client_df[bank_client_df['Net Worth'] >= 5000]
filtered_df

   Client ID  Net Worth
1          2       5000
2          3      10000

In [47]:
# Delete a column from a DataFrame
bank_client_df.drop('Client ID', axis=1, inplace=True)
bank_client_df

   Net Worth
0       1000
1       5000
2      10000
3       3000

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [48]:
high_networth_df = bank_client_df[bank_client_df['Net Worth'] >= 5000]
combined_networth = high_networth_df['Net Worth'].sum()
combined_networth

np.int64(15000)

# TASK #9: PANDAS WITH FUNCTIONS

In [49]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [50]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 

bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444],
'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
'Net worth [$]':[3500, 29000, 10000, 2000],
'Years with bank':[3, 4, 9, 5]})
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [51]:
# You can apply a function to the DataFrame 
def networth_update(net_worth):
    return net_worth * 1.20

In [52]:
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [53]:
def triple_and_add(net_worth):
    return (net_worth * 3) + 200

bank_client_df['Updated Net Worth'] = bank_client_df['Net worth [$]'].apply(triple_and_add)
total_combined_networth = bank_client_df['Updated Net Worth'].sum()
total_combined_networth

np.int64(134300)

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [54]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [55]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444],
'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
'Net worth [$]':[3500, 29000, 10000, 2000],
'Years with bank':[3, 4, 9, 5]})
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [56]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df.sort_values(by='Years with bank')

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [57]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by='Years with bank', inplace=True)
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [58]:
# Note that now the change (ordering) took place 
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [59]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [60]:
bank_df_1 = pd.DataFrame({'Bank client ID': [1, 2, 3, 4, 5],
                          'First Name': ['Ahmad', 'Sarah', 'Mohamed', 'Fatma', 'Ali'],
                          'Last Name': ['Ali', 'Ahmed', 'Hassan', 'Mahmoud', 'Ibrahim']})
bank_df_1

   Bank client ID First Name Last Name
0               1      Ahmad       Ali
1               2      Sarah     Ahmed
2               3    Mohamed    Hassan
3               4      Fatma   Mahmoud
4               5        Ali   Ibrahim

In [61]:
bank_df_2 = pd.DataFrame({'Bank client ID': [6, 7, 8, 9, 10],
                          'First Name': ['Khaled', 'Mariam', 'Omar', 'Nour', 'Youssef'],
                          'Last Name': ['Zaki', 'Adel', 'Said', 'Gamal', 'Tarek']})
bank_df_2

   Bank client ID First Name Last Name
0               6     Khaled      Zaki
1               7     Mariam      Adel
2               8       Omar      Said
3               9       Nour     Gamal
4              10    Youssef     Tarek

In [62]:
bank_df_all = pd.concat([bank_df_1, bank_df_2])
bank_df_all

   Bank client ID First Name Last Name
0               1      Ahmad       Ali
1               2      Sarah     Ahmed
2               3    Mohamed    Hassan
3               4      Fatma   Mahmoud
4               5        Ali   Ibrahim
0               6     Khaled      Zaki
1               7     Mariam      Adel
2               8       Omar      Said
3               9       Nour     Gamal
4              10    Youssef     Tarek

In [63]:
bank_salary_df = pd.DataFrame({'Bank client ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                               'Annual Salary [$]': [30000, 45000, 52000, 60000, 25000, 70000, 48000, 55000, 62000, 40000]})
bank_salary_df

   Bank client ID  Annual Salary [$]
0               1              30000
1               2              45000
2               3              52000
3               4              60000
4               5              25000
5               6              70000
6               7              48000
7               8              55000
8               9              62000
9              10              40000

In [64]:
bank_merged_df = pd.merge(bank_df_all, bank_salary_df, on='Bank client ID')
bank_merged_df

   Bank client ID First Name Last Name  Annual Salary [$]
0               1      Ahmad       Ali              30000
1               2      Sarah     Ahmed              45000
2               3    Mohamed    Hassan              52000
3               4      Fatma   Mahmoud              60000
4               5        Ali   Ibrahim              25000
5               6     Khaled      Zaki              70000
6               7     Mariam      Adel              48000
7               8       Omar      Said              55000
8               9       Nour     Gamal              62000
9              10    Youssef     Tarek              40000

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [65]:
import pandas as pd

Bank_df_1 = pd.DataFrame({
    'Bank Client ID': [1, 2, 3, 4, 5],
    'First Name': ['Nancy', 'Alex', 'Steve', 'Stephanie', 'John'],
    'Last Name': ['Jolie', 'White', 'Angel', 'Walsh', 'Silver']
})

Bank_df_2 = pd.DataFrame({
    'Bank Client ID': [6, 7, 8, 9, 10],
    'First Name': ['Bill', 'Kate', 'Laila', 'Mitch', 'Ryan'],
    'Last Name': ['Glover', 'Geller', 'Mani', 'Gomez', 'East']
})

raw_salary_data = {
    'Bank Client ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Annual Salary [$]': [25000, 35000, 45000, 48000, 67000, 50000, 78000, 90000, 20000, 39000]
}
bank_salary_df = pd.DataFrame(raw_salary_data)

bank_df_all = pd.concat([Bank_df_1, Bank_df_2])

bank_df_all = pd.merge(bank_df_all, bank_salary_df, on='Bank Client ID')

new_client_df = pd.DataFrame({
    'Bank Client ID': [11],
    'First Name': ['Ahmed'],
    'Last Name': ['Hassan'],
    'Annual Salary [$]': [85000]
})

bank_df_all = pd.concat([bank_df_all, new_client_df], ignore_index=True)

bank_df_all

    Bank Client ID First Name Last Name  Annual Salary [$]
0                1      Nancy     Jolie              25000
1                2       Alex     White              35000
2                3      Steve     Angel              45000
3                4  Stephanie     Walsh              48000
4                5       John    Silver              67000
5                6       Bill    Glover              50000
6                7       Kate    Geller              78000
7                8      Laila      Mani              90000
8                9      Mitch     Gomez              20000
9               10       Ryan      East              39000
10              11      Ahmed    Hassan              85000

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [66]:
x = np.array([[3, 7, 9, 3], [4, 3, 2, 2]])
x

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [67]:
x = 10  # Example positive integer for a non-interactive notebook run
x = np.random.randint(0, x + 1, 10)
x

array([ 4,  2,  7,  5, 10,  2,  0,  2,  4,  2])

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [68]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

array([10.29563014, 16.55294536, 20.39607805])

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [69]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

In [70]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [71]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [72]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

  stock ticker symbols  price per share [$]  Number of stocks
0                 AAPL                 3500                 3
1                 AMZN                  200                 4
2                    T                   40                 9

In [73]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

0    10500
1      800
2      360
dtype: int64
Total portfolio value = 11660

MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

In [74]:
# Read tabular data using read_html. A fallback keeps the notebook runnable offline.
url = 'https://www.ssa.gov/oact/progdata/nra.html'
try:
    retirement_age_df = pd.read_html(url)
except Exception as e:
    print(f'Could not retrieve live data; using an illustrative fallback table. Details: {type(e).__name__}')
    retirement_age_df = [pd.DataFrame({'Year': [2024, 2025, 2026],
                                      'Retirement Age': ['66 years 8 months', '66 years 10 months', '67 years']})]
retirement_age_df[0].head()

Could not retrieve live data; using an illustrative fallback table. Details: URLError

   Year      Retirement Age
0  2024   66 years 8 months
1  2025  66 years 10 months
2  2026            67 years

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [75]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
1             222            Steve          29000                4
2             333            Mitch          10000                9

In [76]:
df_high_networth['Net worth [$]'].sum()

np.int64(39000)

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [77]:
def networth_update(balance):
    return balance * 3 + 200

In [78]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

0    10700
1    87200
3     6200
2    30200
Name: Net worth [$], dtype: int64

In [79]:
results.sum()

np.int64(134300)

PROJECT SOLUTION:

In [80]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

  Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000

In [81]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

  Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

In [82]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

  Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000
0             11         Ry        Aly                    1000